/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNILoader */

#ifndef _Included_JNILoader
#define _Included_JNILoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNILoader
 * Method:    greet
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNILoader_greet
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
